import { Montserrat } from "next/font/google";
import "./globals.css";
import Nav from "./home/Nav";

const montserrat = Montserrat({
  subsets: ["latin"],
  variable: "--font-montserrat",
});

export const metadata = {
  title: "Cyber.AI",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={` ${montserrat.variable} antialiased`}
      >
        <Nav></Nav>
        {children}
      </body>
    </html>
  );
}
